export type LatLng={lat:number;lng:number};
export type RouteResult={distanceMeters:number;durationSeconds:number;geometry?:[number,number][];provider:'mapbox'|'fallback'};
const MAPBOX='https://api.mapbox.com';
const token=()=>process.env.NEXT_PUBLIC_MAPBOX_TOKEN||'';
export function haversineMeters(a:LatLng,b:LatLng){const R=6371008.8;const p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180;const h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
export async function routeBetween(points:LatLng[],options:{profile?:'driving'|'driving-traffic'}={}):Promise<RouteResult>{if(points.length<2)throw new Error('route requires at least two points');const t=token();if(!t){const d=points.slice(1).reduce((sum,p,i)=>sum+haversineMeters(points[i],p),0);return {distanceMeters:d,durationSeconds:Math.max(60,Math.round(d/7)),provider:'fallback'}}const coords=points.map(p=>p.lng+','+p.lat).join(';');const profile=options.profile||'driving-traffic';const res=await fetch(MAPBOX+'/directions/v5/mapbox/'+profile+'/'+coords+'?alternatives=false&geometries=geojson&overview=full&steps=false&access_token='+encodeURIComponent(t),{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('routing_unavailable:'+res.status);const j=await res.json();const r=j.routes?.[0];if(!r)throw new Error('route_not_found');return {distanceMeters:r.distance,durationSeconds:r.duration,geometry:r.geometry?.coordinates?.map((c:[number,number])=>[c[1],c[0]]),provider:'mapbox'}}
export async function reverseGeocode(p:LatLng){const t=token();if(!t)return null;const res=await fetch(MAPBOX+'/search/geocode/v6/reverse?longitude='+p.lng+'&latitude='+p.lat+'&limit=1&access_token='+encodeURIComponent(t));if(!res.ok)return null;const j=await res.json();return j.features?.[0]?.properties?.full_address||j.features?.[0]?.properties?.name||null}
export function navigationUrl(p:LatLng,provider:'google'|'apple'|'waze'='google'){const q=p.lat+','+p.lng;if(provider==='waze')return 'https://www.waze.com/ul?ll='+encodeURIComponent(q)+'&navigate=yes';if(provider==='apple')return 'http://maps.apple.com/?daddr='+encodeURIComponent(q);return 'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(q)+'&travelmode=driving'}
export function formatDistance(m:number){return m<1000?Math.round(m/10)*10+' m':(m/1000).toFixed(1)+' km'}
export function formatDuration(s:number){const m=Math.max(1,Math.round(s/60));return m<60?m+' min':Math.floor(m/60)+'h '+m%60+'m'}
