"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "../../../lib/supabase";
type Photo={id:string;driver_id:string;storage_path:string;created_at:string;status:string;rejection_reason:string|null};
export default function AdminDriverPhotos(){
 const [allowed,setAllowed]=useState(false),[checking,setChecking]=useState(true),[photos,setPhotos]=useState<Photo[]>([]),[urls,setUrls]=useState<Record<string,string>>({}),[busy,setBusy]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[reason,setReason]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{setError("");const {data,error:e}=await supabase.from("driver_profile_photos").select("id,driver_id,storage_path,created_at,status,rejection_reason").eq("status","pending_review").order("created_at",{ascending:true}).limit(100);if(e){setError("Unable to load pending photos.");return;}const list=(data||[]) as Photo[];setPhotos(list);const pairs=await Promise.all(list.map(async p=>{const {data:url}=await supabase.storage.from("nexride-driver-photos").createSignedUrl(p.storage_path,300);return [p.id,url?.signedUrl||""] as const;}));setUrls(Object.fromEntries(pairs));},[]);
 useEffect(()=>{let active=true;(async()=>{const {data}=await supabase.auth.getUser();if(!data.user){if(active)setChecking(false);return;}const {data:profile}=await supabase.from("profiles").select("role,account_status").eq("id",data.user.id).maybeSingle();if(!active)return;const ok=profile?.role==="admin"&&profile?.account_status==="active";setAllowed(ok);setChecking(false);if(ok)await load();})();return()=>{active=false;};},[load]);
 const review=async(id:string,approve:boolean)=>{const why=reason[id]?.trim()||"";if(!approve&&!why){setError("Enter a rejection reason.");return;}setBusy(id);setError("");setMessage("");const {error:e}=await supabase.rpc("review_driver_profile_photo",{p_photo_id:id,p_approve:approve,p_reason:approve?null:why});if(e)setError(e.message);else{setMessage(approve?"Photo approved.":"Photo rejected.");await load();}setBusy("");};
 if(checking)return <main style={{padding:24}}>Checking administrator access…</main>;
 if(!allowed)return <main style={{padding:24}}><h1>Access restricted</h1><p>Only authorized NexRide administrators can review driver photos.</p><Link href="/admin">Admin sign in</Link></main>;
 return <main style={{maxWidth:920,margin:"auto",padding:"24px 16px",color:"inherit"}}><Link href="/admin">← Admin dashboard</Link><h1>Driver photo verification</h1><p>Review each driver's submitted photo before it becomes visible to riders. Approved images remain private in Storage.</p><button onClick={()=>void load()}>Refresh queue</button>{error&&<p role="alert" style={{color:"#d75a5a"}}>{error}</p>}{message&&<p role="status">{message}</p>}{photos.length===0&&<p>No photos are awaiting review.</p>}<div style={{display:"grid",gap:16,marginTop:20}}>{photos.map(photo=><section key={photo.id} style={{border:"1px solid #8b9eae",borderRadius:16,padding:16,display:"flex",flexWrap:"wrap",gap:18}}>{urls[photo.id]?<img src={urls[photo.id]} alt="Submitted driver portrait awaiting review" style={{width:160,height:160,objectFit:"cover",borderRadius:16}}/>:<div>Photo preview unavailable. Refresh to retry.</div>}<div style={{flex:"1 1 240px"}}><strong>Driver ID: {photo.driver_id}</strong><p>Submitted {new Date(photo.created_at).toLocaleString()}</p><label htmlFor={"reason-"+photo.id}>Rejection reason</label><textarea id={"reason-"+photo.id} value={reason[photo.id]||""} onChange={e=>setReason(s=>({...s,[photo.id]:e.target.value}))} placeholder="Required when rejecting" style={{display:"block",width:"100%",minHeight:70,margin:"8px 0",color:"#111"}}/><div style={{display:"flex",gap:8}}><button disabled={busy===photo.id||!urls[photo.id]} onClick={()=>void review(photo.id,true)}>Approve</button><button disabled={busy===photo.id} onClick={()=>void review(photo.id,false)}>Reject</button></div></div></section>)}</div></main>;
}