-- NexRide integration migration for the existing DriverSuperApp Supabase project.
-- Target project: mrbgtdrpscdoxwdgvfcs
-- This migration extends the existing production schema instead of creating a parallel ride-hailing schema.

create extension if not exists pgcrypto;
create extension if not exists postgis;

alter table public.trips
  add column if not exists client_request_id text,
  add column if not exists cancelled_by uuid,
  add column if not exists cancellation_reason text,
  add column if not exists pickup_address text,
  add column if not exists destination_address text,
  add column if not exists actual_fare_minor bigint,
  add column if not exists currency text not null default 'ETB',
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists trips_client_request_id_uq
  on public.trips(customer_id, client_request_id)
  where client_request_id is not null;
create index if not exists trips_driver_state_idx on public.trips(driver_id,state,requested_at desc);
create index if not exists trips_city_state_requested_idx on public.trips(city_id,state,requested_at desc);

create table if not exists public.ride_events (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  actor_id uuid references public.profiles(id),
  event_type text not null,
  from_state text,
  to_state text,
  metadata jsonb not null default '{}'::jsonb,
  idempotency_key text,
  created_at timestamptz not null default now()
);
create unique index if not exists ride_events_idempotency_uq on public.ride_events(trip_id,idempotency_key) where idempotency_key is not null;
create index if not exists ride_events_trip_created_idx on public.ride_events(trip_id,created_at desc);

create table if not exists public.ride_locations (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.trips(id) on delete cascade,
  actor_id uuid references public.profiles(id),
  location geography(Point,4326) not null,
  heading double precision,
  speed_mps double precision,
  accuracy_m double precision,
  recorded_at timestamptz not null default now()
);
create index if not exists ride_locations_trip_time_idx on public.ride_locations(trip_id,recorded_at desc);
create index if not exists ride_locations_geo_idx on public.ride_locations using gist(location);

create table if not exists public.ride_shares (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  created_by uuid not null references public.profiles(id),
  token_hash text not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists ride_shares_trip_idx on public.ride_shares(trip_id,expires_at desc);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid references public.trips(id),
  customer_id uuid not null references public.profiles(id),
  provider text not null,
  provider_payment_id text,
  idempotency_key text not null,
  amount_minor bigint not null check(amount_minor>=0),
  currency text not null default 'ETB',
  status text not null default 'pending' check(status in ('pending','authorized','paid','failed','refunded','cancelled')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider,provider_payment_id),
  unique(customer_id,idempotency_key)
);
create index if not exists payments_trip_idx on public.payments(trip_id,created_at desc);
create index if not exists payments_customer_idx on public.payments(customer_id,created_at desc);

create table if not exists public.driver_payouts (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.drivers(id),
  amount_minor bigint not null check(amount_minor>=0),
  currency text not null default 'ETB',
  status text not null default 'pending' check(status in ('pending','processing','paid','failed','cancelled')),
  provider text,
  provider_payout_id text,
  idempotency_key text unique,
  metadata jsonb not null default '{}'::jsonb,
  requested_at timestamptz not null default now(),
  processed_at timestamptz
);
create index if not exists driver_payouts_driver_status_idx on public.driver_payouts(driver_id,status,requested_at desc);

create table if not exists public.ratings (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  rater_id uuid not null references public.profiles(id),
  ratee_id uuid not null references public.profiles(id),
  score smallint not null check(score between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique(trip_id,rater_id)
);
create index if not exists ratings_ratee_idx on public.ratings(ratee_id,created_at desc);

create table if not exists public.notification_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  platform text not null check(platform in ('android','ios','web')),
  push_token text not null unique,
  locale text not null default 'en' check(locale in ('en','am')),
  enabled boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists notification_devices_user_enabled_idx on public.notification_devices(user_id,enabled);

create table if not exists public.promo_redemptions (
  id uuid primary key default gen_random_uuid(),
  promo_id uuid not null references public.promo_codes(id),
  user_id uuid not null references public.profiles(id),
  trip_id uuid references public.trips(id),
  discount_minor bigint not null check(discount_minor>=0),
  redeemed_at timestamptz not null default now()
);
create unique index if not exists promo_redemptions_trip_uq on public.promo_redemptions(promo_id,trip_id) where trip_id is not null;
create unique index if not exists promo_redemptions_user_active_uq on public.promo_redemptions(promo_id,user_id) where trip_id is null;

create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(),
  referrer_id uuid not null references public.profiles(id),
  referred_id uuid not null references public.profiles(id),
  code text not null unique,
  status text not null default 'pending' check(status in ('pending','qualified','rewarded','expired')),
  reward_minor bigint not null default 0 check(reward_minor>=0),
  qualified_at timestamptz,
  rewarded_at timestamptz,
  created_at timestamptz not null default now(),
  unique(referrer_id,referred_id)
);

create table if not exists public.incentives (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid references public.drivers(id),
  city_id uuid references public.cities(id),
  title text not null,
  description text,
  target_trips integer,
  target_earnings_minor bigint,
  reward_minor bigint not null default 0 check(reward_minor>=0),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'active' check(status in ('draft','active','completed','cancelled','expired')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists incentives_driver_active_idx on public.incentives(driver_id,status,starts_at,ends_at);
create index if not exists incentives_city_active_idx on public.incentives(city_id,status,starts_at,ends_at);

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id),
  trip_id uuid references public.trips(id),
  category text not null,
  subject text not null,
  description text not null,
  status text not null default 'open' check(status in ('open','in_progress','resolved','closed')),
  priority text not null default 'normal' check(priority in ('low','normal','high','urgent')),
  assigned_to uuid references public.profiles(id),
  resolution text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists support_tickets_queue_idx on public.support_tickets(status,priority,created_at desc);

create table if not exists public.safety_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id),
  trip_id uuid references public.trips(id),
  category text not null,
  severity text not null default 'medium' check(severity in ('low','medium','high','critical')),
  description text,
  status text not null default 'open' check(status in ('open','investigating','resolved','closed')),
  assigned_to uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index if not exists safety_reports_queue_idx on public.safety_reports(status,severity,created_at desc);

create table if not exists public.app_translations (
  id uuid primary key default gen_random_uuid(),
  locale text not null check(locale in ('en','am')),
  translation_key text not null,
  translation_value text not null,
  updated_at timestamptz not null default now(),
  unique(locale,translation_key)
);

create table if not exists public.idempotency_keys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  key text not null,
  scope text not null,
  request_hash text,
  response_status integer,
  response_body jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  unique(user_id,scope,key)
);
create index if not exists idempotency_keys_expiry_idx on public.idempotency_keys(expires_at);

create or replace function public.nexride_set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end $$;

drop trigger if exists trips_nexride_updated_at on public.trips;
create trigger trips_nexride_updated_at before update on public.trips for each row execute function public.nexride_set_updated_at();
drop trigger if exists payments_nexride_updated_at on public.payments;
create trigger payments_nexride_updated_at before update on public.payments for each row execute function public.nexride_set_updated_at();
drop trigger if exists support_tickets_nexride_updated_at on public.support_tickets;
create trigger support_tickets_nexride_updated_at before update on public.support_tickets for each row execute function public.nexride_set_updated_at();

alter table public.ride_events enable row level security;
alter table public.ride_locations enable row level security;
alter table public.ride_shares enable row level security;
alter table public.payments enable row level security;
alter table public.driver_payouts enable row level security;
alter table public.ratings enable row level security;
alter table public.notification_devices enable row level security;
alter table public.promo_redemptions enable row level security;
alter table public.referrals enable row level security;
alter table public.incentives enable row level security;
alter table public.support_tickets enable row level security;
alter table public.safety_reports enable row level security;
alter table public.app_translations enable row level security;
alter table public.idempotency_keys enable row level security;

create policy ride_events_select_participant on public.ride_events for select to authenticated using (
  exists(select 1 from public.trips t where t.id=trip_id and (t.customer_id=auth.uid() or t.driver_id=auth.uid()))
);
create policy ride_locations_select_participant on public.ride_locations for select to authenticated using (
  exists(select 1 from public.trips t where t.id=trip_id and (t.customer_id=auth.uid() or t.driver_id=auth.uid()))
);
create policy ride_shares_owner on public.ride_shares for all to authenticated using(created_by=auth.uid()) with check(created_by=auth.uid());
create policy payments_owner on public.payments for select to authenticated using(customer_id=auth.uid());
create policy payouts_driver on public.driver_payouts for select to authenticated using(exists(select 1 from public.drivers d where d.id=driver_id and d.id=auth.uid()));
create policy ratings_participant on public.ratings for select to authenticated using(rater_id=auth.uid() or ratee_id=auth.uid());
create policy ratings_create on public.ratings for insert to authenticated with check(rater_id=auth.uid());
create policy notification_devices_owner on public.notification_devices for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy promo_redemptions_owner on public.promo_redemptions for select to authenticated using(user_id=auth.uid());
create policy referrals_participant on public.referrals for select to authenticated using(referrer_id=auth.uid() or referred_id=auth.uid());
create policy incentives_driver_read on public.incentives for select to authenticated using(driver_id=auth.uid() or driver_id is null);
create policy support_requester_read on public.support_tickets for select to authenticated using(requester_id=auth.uid() or assigned_to=auth.uid());
create policy support_requester_create on public.support_tickets for insert to authenticated with check(requester_id=auth.uid());
create policy safety_reporter_read on public.safety_reports for select to authenticated using(reporter_id=auth.uid() or assigned_to=auth.uid());
create policy safety_reporter_create on public.safety_reports for insert to authenticated with check(reporter_id=auth.uid());
create policy translations_authenticated_read on public.app_translations for select to authenticated using(true);
create policy idempotency_owner on public.idempotency_keys for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='ride_events') then
    execute 'alter publication supabase_realtime add table public.ride_events';
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='ride_locations') then
    execute 'alter publication supabase_realtime add table public.ride_locations';
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='payments') then
    execute 'alter publication supabase_realtime add table public.payments';
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then
    execute 'alter publication supabase_realtime add table public.notifications';
  end if;
end $$;